epochs: 300
attackType: 'ab'
model_name: 'stgcn_kinetics'
data_path: './train_data_joint.npy'
num_frame_path:
label_path: './train_label.pkl'
save_path: './smattack/stgcn/kinetics/'
batch_size: 16
classNum: 400
dataset: 'kinetics'
lr: 0.0005
task: ''