epochs: 300
attackType: 'ab'
model_name: 'stgcn120'
data_path: './xsub/train_data_joint.npy'
num_frame_path: './xsub/train_num_frame.npy'
label_path: './xsub/train_label.pkl'
save_path: './smattack/stgcn/ntu120-cs-train/'
batch_size: 16
classNum: 120
dataset: 'ntu120'
lr: 0.0005
task: ''